version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-2)
  build:
    commands:
      - echo build Docker image on `date`
      - cd src
      - docker-compose build -t devops-project:latest .
      - docker-compose tag devops-project:latest 532004891226.dkr.ecr.eu-west-2.amazonaws.com/devops-project:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker-compose push 532004891226.dkr.ecr.eu-west-2.amazonaws.com/devops-project:latest