apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: app-deployment 
spec: 
  selector: 
    matchLabels: 
      app: docker-compose-image-compressor 
  replicas: 5 # tells deployment to run 5 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: docker-compose-image-compressor 
    spec: 
      containers: 
      - name: docker-compose-image-compressor 
        image: o3cloudng/test-react-image-compressor-app:1
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: app-service 
spec: 
  selector: 
    app: docker-compose-image-compressor 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 31000 
  type: NodePort

# kubectl apply -f deployment.yaml