version: '3.7'

services:

  react-image-compressor:
    container_name: docker-compose-image-compressor
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=development